In [ ]:
# Öğrenci bilgileri alınarak final notunu tahmin eden uygulama 

In [1]:
import pandas as pd

In [12]:
#Datasetin csv dosyası olarak okunması
veri=pd.read_csv('student-mat.csv', sep=';')

In [20]:
#İstenilen özelliklerin seçilmesi.
veri=veri[['G1','G2','G3','studytime','failures','absences','age']]

In [23]:
veri.head(11)

G1  G2  G3  studytime  failures  absences  age
0    5   6   6          2         0         6   18
1    5   5   6          2         0         4   17
2    7   8  10          2         3        10   15
3   15  14  15          3         0         2   15
4    6  10  10          2         0         4   16
5   15  15  15          2         0        10   16
6   12  12  11          2         0         0   16
7    6   5   6          2         0         6   17
8   16  18  19          2         0         0   15
9   14  15  15          2         0         0   15
10  10   8   9          2         0         0   15

In [24]:
#Sutun adlarının türkçelştirilmesi ve satırlarda ki verierin korunması
veri.rename(columns={'G1': 'Vize1','G2': 'Vize2','G3': 'Final',
                     'studytime': 'Calisma_Suresi','failures': 'Sinif_Tekrari','absences': 'Devamsizlik','age': 'Yas'},
           inplace=True)

In [25]:
veri.head(11)

Vize1  Vize2  Final  Calisma_Suresi  Sinif_Tekrari  Devamsizlik  Yas
0       5      6      6               2              0            6   18
1       5      5      6               2              0            4   17
2       7      8     10               2              3           10   15
3      15     14     15               3              0            2   15
4       6     10     10               2              0            4   16
5      15     15     15               2              0           10   16
6      12     12     11               2              0            0   16
7       6      5      6               2              0            6   17
8      16     18     19               2              0            0   15
9      14     15     15               2              0            0   15
10     10      8      9               2              0            0   15

In [27]:
veri.dtypes

Vize1             int64
Vize2             int64
Final             int64
Calisma_Suresi    int64
Sinif_Tekrari     int64
Devamsizlik       int64
Yas               int64
dtype: object

In [28]:
#Girdi ve çıktı değerlerinin oluşturulması.
import numpy as np
y=np.array(veri['Final'])
X=np.array(veri.drop('Final',axis=1))

In [29]:
from sklearn.model_selection import train_test_split

In [32]:
#Eğitim ve test verilerinin bölünmesi.
X_egitim, X_test, y_egitim, y_test = train_test_split(X,y, test_size=0.2, random_state=2)

In [33]:
#Doğrusal Regresyon
from sklearn.linear_model import LinearRegression

In [34]:
linear=LinearRegression()

In [35]:
linear.fit(X_egitim,y_egitim)

LinearRegression()

In [36]:
#Model ½83 oranında doğru tahmin yapıyor
linear.score(X_test,y_test)

0.8325898318712226

In [37]:
linear.score(X_egitim,y_egitim)

0.8261275475197141

In [38]:
#Test oranı ve egitim oranının birbirine yakın olması beklenir

In [40]:
print('Katsayılar: \n',linear.coef_)
print('Sabit: \n', linear.intercept_)

Katsayılar: 
 [ 0.19575962  0.95558174 -0.24215827  0.12730705  0.03566925 -0.23224281]
Sabit: 
 2.1549097406751496


In [41]:
veri.head(11)

Vize1  Vize2  Final  Calisma_Suresi  Sinif_Tekrari  Devamsizlik  Yas
0       5      6      6               2              0            6   18
1       5      5      6               2              0            4   17
2       7      8     10               2              3           10   15
3      15     14     15               3              0            2   15
4       6     10     10               2              0            4   16
5      15     15     15               2              0           10   16
6      12     12     11               2              0            0   16
7       6      5      6               2              0            6   17
8      16     18     19               2              0            0   15
9      14     15     15               2              0            0   15
10     10      8      9               2              0            0   15

In [42]:
#ilk notu 10 ikinci notu 14 çalışma süresi 3 sınıf tekrarı 0 devamsızlığı 4 yaşı 16 olan bir öğrencinin final notunu tahmin etme.
yeni_veri=np.array([[10,14,3,0,4,16]])
linear.predict(yeni_veri)

array([13.19096755])

In [43]:
#0. veri için final notu 6 modelimiz 4.4 buluyor.
yeni_veri2=np.array([[5,6,2,0,6,18]])
linear.predict(yeni_veri2)

array([4.41652664])

In [44]:
#1. veri için final notu 6 modelimiz 3.6 buluyor.
yeni_veri3=np.array([[5,5,2,0,4,17]])
linear.predict(yeni_veri3)

array([3.62184922])

In [45]:
#5. veri için final notu 15 modelimiz 15.6 buluyor.
yeni_veri4=np.array([[15,15,2,0,10,16]])
linear.predict(yeni_veri4)

array([15.58152115])

In [46]:
#6. veri için final notu 11 modelimiz 11.8 buluyor.
yeni_veri5=np.array([[12,12,2,0,0,16]])
linear.predict(yeni_veri5)

array([11.7708046])

In [48]:
#rastgele bir veri
yeni_veri6=np.array([[6,18,3,0,5,18]])
linear.predict(yeni_veri6)

array([15.80143963])

In [49]:
#10. veri için final notu 9 modelimiz 7.8 buluyor.
yeni_veri7=np.array([[10,8,2,0,0,15]])
linear.predict(yeni_veri7)

array([7.7892012])